### ISSUE TITLE
`GenomeInfoDb::loadTaxonomy()` fails because of additional column in `specData`

### ISSUE THREAD

**Issue by csoneson** [Bioconductor/GenomeInfoDbData#2]
Hi - there seems to be an issue with the `specData` object in the current version (for Bioc 3.13), causing `GenomeInfoDb::loadTaxonomy()` to fail: 

```
> taxdb <- loadTaxonomyDb()
Error in loadTaxonomyDb() : 
  identical(colnames(taxdb), c("tax_id", "genus", "species")) is not TRUE
```

Indeed, if I load `specData.rda` it has four columns (whereas the previous version had only three):

```
> head(specData, 1)
  tax_id        genus     species ngsAsFactors
1      1          all        <NA>        FALSE
```

Not sure whether the appropriate solution is to just change the check in [GenomeInfoDb::loadTaxonomyDb](https://github.com/Bioconductor/GenomeInfoDb/blob/2eee6d70ab79a3c78d2ab45365045ea8312d6920/R/loadTaxonomyDb.R#L21) (although I wonder if the four columns are intentional, or maybe a misspecified `stringsAsFactors`), or whether there are other implications. 

Thanks!

**Comment by hpages** [comment]
Thanks Charlotte. Also seen on the [3.13 daily report](https://bioconductor.org/checkResults/3.13/bioc-LATEST/GenomeInfoDb/) and [here](https://github.com/Bioconductor/Contributions/issues/2090#issuecomment-834089563).

@Kayla-Morrell @lshep This seems to be related to the recent update of **GenomeInfoData**. Can you take a look? Thanks

**Comment by lshep** [comment]
This seems like its an issue with the updated to specData.rda In GenomeInfoDbData.  I'm rerunning the script now, it looks like it generates correctly with the correct three columns so I'm not sure what happened on the previous update.  we will propagate the new version of the annotation package later today

**Comment by Kayla-Morrell** [comment]
The new version of GenomeInfoDbData (v1.2.6) should now be available and should fix this issue.

**Comment by csoneson** [comment]
Thanks! Looking at today's build reports, this seems to have fixed the issue on Windows and Mac, but somehow it remains on [`nebbiolo1`](http://bioconductor.org/checkResults/devel/bioc-LATEST/GenomeInfoDb/nebbiolo1-checksrc.html)

**Comment by hpages** [comment]
Interesting! It seems that **GenomeInfoDbData** 1.2.6 got pushed to the data annotation package repo right after the builds started on Monday. The builds on riesling1 and machv2 were able to install this new version but not nebbiolo1 (nebbiolo1 still used **GenomeInfoDbData** 1.2.5 for Monday's builds). That's because nebbiolo1 is faster than the other builders so it does things earlier than the other builders. In this case it tried to update **GenomeInfoDbData** a little bit too early when the new version was not yet available.

If everything goes well this issue should go away on today's report.

**Comment by lshep** [comment]
All green on Wed report.  Let us know if anything still seems out of sorts.
